# 工作流的名字
name: Deploy VitePress site to Pages

# 触发条件：当你向 main 分支 push 代码时执行
on:
  push:
    branches: [main]

# 授予机器人发布页面的权限
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # 第一步：拉取代码
        uses: actions/checkout@v4

      - name: Install Node.js # 第二步：安装 Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies # 第三步：安装项目依赖
        run: npm install

      - name: Build # 第四步：构建静态文件
        run: npm run docs:build

      - name: Upload # 第五步：把打包好的文件传给 GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist # 这里的路径要和 VitePress 打包出来的目录一致

  deploy:
    needs: build # 等 build 任务成功后才开始
    runs-on: ubuntu-latest
    steps:
      - name: Deploy # 最后一步：正式发布上线
        id: deployment
        uses: actions/deploy-pages@v4
